package com.s1410.calme.Domain.Utils;

public enum Specialty {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    GERIATRICS,
    GYNECOLOGY,
    HEMATOLOGY,
    INTERNAL_MEDICINE,
    NEPHROLOGY,
    NEUROLOGY,
    OPHTHALMOLOGY,
    ONCOLOGY,
    ORTHOPEDICS,
    OTOLARYNGOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    RADIOLOGY,
    RHEUMATOLOGY,
    TRAUMATOLOGY,
    UROLOGY
}
